version: "3.8"

services:
  weblibdb:
    image: "postgres:12.3"
    environment:
      - POSTGRES_DB=weblib
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
  weblibapi:
    build: .
    command: bash start.sh
    ports:
      - "8090:8090"
      - "5005:5005"
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - GRADLE_OPTS=-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=*:5005
    volumes:
      - .:/weblib
    depends_on:
      - weblibdb

volumes:
  postgres:
